import * as ar from './locales/ar';
import * as da from './locales/da';
import * as de from './locales/de';
import * as es from './locales/es';
import * as fr from './locales/fr';
import * as he from './locales/he';
import * as id from './locales/id';
import * as it from './locales/it';
import * as nb from './locales/nb';
import * as nl from './locales/nl';
import * as pt from './locales/pt';
import * as tr from './locales/tr';
import * as lt from './locales/lt';
import * as pl from './locales/pl';
import * as sk from './locales/sk';
import * as ru from './locales/ru';
import * as cs from './locales/cs';
import * as uz from './locales/uz';
import * as vi from './locales/vi';

export { ar, da, de, es, fr, he, id, it, nb, nl, pt, tr, lt, pl, sk, ru, cs, uz, vi };
